changelog:
  exclude:
    authors:
      - github-actions
  categories:
    - title: Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - bugfix
    - title: Bug Fix
      labels:
        - bugfix
    - title: Dependencies
      labels:
        - dependencies